<a href="https://colab.research.google.com/github/tanvirrahmanaz/Phitron/blob/main/numpyPhitron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
arr = [ 1, 2, 3]
print(arr * 5)

arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [18]:
import numpy as np

# Task
Explain 1D, 2D, and 3D arrays with two examples each using NumPy, and list and explain common NumPy array attributes.

## Explain 1d arrays

### Subtask:
Describe what a 1D array is and provide two examples using NumPy.


**Reasoning**:
Explain what a 1D array is and provide two examples using NumPy as requested in the instructions.



In [14]:
print("A 1D array, also known as a vector, is a sequence of elements arranged in a single row or column. It has only one dimension.")

# Example 1: A 1D array of numbers
array_1d_numbers = np.array([10, 20, 30, 40, 50])
print("\nExample 1 (1D array of numbers):")
print(array_1d_numbers)

# Example 2: A 1D array of strings
array_1d_strings = np.array(["apple", "banana", "cherry", "date"])
print("\nExample 2 (1D array of strings):")
print(array_1d_strings)

A 1D array, also known as a vector, is a sequence of elements arranged in a single row or column. It has only one dimension.

Example 1 (1D array of numbers):
[10 20 30 40 50]

Example 2 (1D array of strings):
['apple' 'banana' 'cherry' 'date']


## Explain 2d arrays

### Subtask:
Describe what a 2D array is and provide two examples using NumPy.


**Reasoning**:
Print the description of a 2D array and then create and print two examples using NumPy arrays as instructed.



In [15]:
print("A 2D array, also known as a matrix, is a collection of elements arranged in rows and columns. It has two dimensions.")

# Example 1: A 2D array of numbers
array_2d_numbers = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nExample 1 (2D array of numbers):")
print(array_2d_numbers)

# Example 2: A 2D array of strings
array_2d_strings = np.array([["apple", "banana"], ["cherry", "date"]])
print("\nExample 2 (2D array of strings):")
print(array_2d_strings)

A 2D array, also known as a matrix, is a collection of elements arranged in rows and columns. It has two dimensions.

Example 1 (2D array of numbers):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Example 2 (2D array of strings):
[['apple' 'banana']
 ['cherry' 'date']]


## Explain 3d arrays

### Subtask:
Describe what a 3D array is and provide two examples using NumPy.


**Reasoning**:
Print the description of a 3D array and then create and print two examples of 3D NumPy arrays as requested, one with numerical data and one with string data, adding comments to explain each.



In [16]:
print("A 3D array is a collection of elements arranged in rows, columns, and layers (or depth). It has three dimensions and can be thought of as a stack of 2D arrays.")

# Example 1: A 3D array of numbers
# This array has 2 layers, each layer has 2 rows, and each row has 3 columns.
array_3d_numbers = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("\nExample 1 (3D array of numbers):")
print(array_3d_numbers)

# Example 2: A 3D array of strings
# This array has 1 layer, each layer has 2 rows, and each row has 2 columns.
array_3d_strings = np.array([[["apple", "banana"], ["cherry", "date"]]])
print("\nExample 2 (3D array of strings):")
print(array_3d_strings)

A 3D array is a collection of elements arranged in rows, columns, and layers (or depth). It has three dimensions and can be thought of as a stack of 2D arrays.

Example 1 (3D array of numbers):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Example 2 (3D array of strings):
[[['apple' 'banana']
  ['cherry' 'date']]]


## Explain numpy attributes

### Subtask:
List and explain key NumPy array attributes like shape, dtype, ndim, and size.


**Reasoning**:
Print a heading and then iterate through the key NumPy array attributes, explaining each one and showing its value for a sample array.



In [17]:
print("--- Key NumPy Array Attributes ---")

# Using array_3d_numbers as an example
example_array = array_3d_numbers

# shape
print("\nAttribute: shape")
print("Explanation: The 'shape' attribute returns a tuple indicating the size of the array in each dimension.")
print(f"Value for the example array: {example_array.shape}")

# dtype
print("\nAttribute: dtype")
print("Explanation: The 'dtype' attribute returns the data type of the elements in the array.")
print(f"Value for the example array: {example_array.dtype}")

# ndim
print("\nAttribute: ndim")
print("Explanation: The 'ndim' attribute returns the number of dimensions of the array.")
print(f"Value for the example array: {example_array.ndim}")

# size
print("\nAttribute: size")
print("Explanation: The 'size' attribute returns the total number of elements in the array.")
print(f"Value for the example array: {example_array.size}")

--- Key NumPy Array Attributes ---

Attribute: shape
Explanation: The 'shape' attribute returns a tuple indicating the size of the array in each dimension.
Value for the example array: (2, 2, 3)

Attribute: dtype
Explanation: The 'dtype' attribute returns the data type of the elements in the array.
Value for the example array: int64

Attribute: ndim
Explanation: The 'ndim' attribute returns the number of dimensions of the array.
Value for the example array: 3

Attribute: size
Explanation: The 'size' attribute returns the total number of elements in the array.
Value for the example array: 12


## Summary:

### Data Analysis Key Findings

*   A 1D array (vector) is a sequence of elements in a single dimension. Examples included `[10, 20, 30, 40, 50]` and `["apple", "banana", "cherry", "date"]`.
*   A 2D array (matrix) is a collection of elements arranged in rows and columns. Examples included `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]` and `[["apple", "banana"], ["cherry", "date"]]`.
*   A 3D array is a collection of elements arranged in rows, columns, and layers, viewed as a stack of 2D arrays. Examples included `[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]` and `[[["apple", "banana"], ["cherry", "date"]]]`.
*   Key NumPy array attributes demonstrated using a 3D array with shape (2, 2, 3), dtype int64, ndim 3, and size 12:
    *   `shape`: Returns a tuple indicating the size of the array in each dimension (e.g., (2, 2, 3)).
    *   `dtype`: Returns the data type of the elements in the array (e.g., int64).
    *   `ndim`: Returns the number of dimensions of the array (e.g., 3).
    *   `size`: Returns the total number of elements in the array (e.g., 12).

### Insights or Next Steps

*   Understanding array dimensions and attributes is fundamental for manipulating and analyzing data using NumPy.
*   Further exploration could involve demonstrating how to perform operations on arrays of different dimensions and how these attributes change after operations like reshaping or slicing.
