<a href="https://colab.research.google.com/github/tanvirrahmanaz/Phitron/blob/main/Tanvir_Rahman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


Q1. Create NumPy arrays from the ages and salaries data generated above. Print both arrays and display their dtype, ndim, shape, and size.


In [ ]:
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)

print(ages)
print(salaries,"\n")

print("dtype")
print(ages.dtype)
print(salaries.dtype)

print("\n")
print("ndim")
print(ages.ndim)
print(salaries.ndim)

print("\n")
print("shape")
print(ages.shape)
print(salaries.shape)

print("\n")
print("size")
print(ages.size)
print(salaries.size)

[26 54 50 59 41 32 49 49 41 58]
[82915 84384 81005 76576 69353 47675 82733 74417 53938 53664] 

dtype
int64
int64


ndim
1
1


shape
(10,)
(10,)


size
10
10


Q2. Using the salaries array, find and print the highest and lowest salary values. Also, calculate and print the average salary and age using NumPy functions.

In [ ]:
print(salaries.max())
print(salaries.min())

print(np.average(salaries))
print(np.average(ages))

84384
47675
70666.0
45.9


Q3. From the ages array, filter and print all ages greater than 30 using a boolean condition. Then count and print how many employees are older than 30.

In [ ]:
ages_greater_than_30 = ages[ages > 30]
print(ages_greater_than_30)

count = np.sum(ages > 30)
print(count)

[54 50 59 41 32 49 49 41 58]
9


Q4. Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array). Print the new updated ages array.

In [ ]:
update_ages = ages + 5
print(update_ages)
ages

[31 59 55 64 46 37 54 54 46 63]


array([26, 54, 50, 59, 41, 32, 49, 49, 41, 58])

Q5. Using NumPy, calculate the total salary expense (sum of all salaries) and the difference between the maximum and minimum salary. Print both results.

In [ ]:
total_salary= sum(salaries)
print(total_salary)

max_salary = salaries.max()
min_salary = salaries.min()
print(max_salary, min_salary)

diff = max_salary - min_salary
print(diff)

706660
84384 47675
36709


##Pandas

Q6. Load the employees.csv file into a Pandas DataFrame. Display the first 5 rows, and check basic info using info() and summary statistics using describe().

In [ ]:
df = pd.read_csv("employees.csv")
print(" \n")
print(df.head())
print(" \n")

print(df.info())
print(" \n")

print(df.describe())


 

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None
 

             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


Q7. Display only the id, age, and salary columns. Then show the last 3 rows using tail().


In [ ]:
subset = df[["id", "age", "salary"]]
print(subset)

print("\nLast 3 rows:")
print(subset.tail(3))

   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311

Last 3 rows:
   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311


Q8. Filter the DataFrame to show only employees who work in the IT department. Print the result and show the total number of IT employees.

In [ ]:
it_employees = df[df["dept"] == "IT"]
total_it_employees = len(it_employees)

print(it_employees,"\n")
print(total_it_employees)

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT 

3


Q9. Sort the DataFrame by salary in descending order and display the top 3 highest-paid employees along with their department and age.


In [ ]:
sorted_df = df.sort_values(by="salary", ascending=False)
top_3_employees = sorted_df.head(3)

print(top_3_employees)

   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR


Q10. Replace all salary values greater than 80000 with 80000 using loc. Then calculate and print the new average salary of all employees after replacement.

In [ ]:
df.loc[df["salary"] > 80000, "salary"] = 80000

new_average_salary = df["salary"].mean()

print(new_average_salary)


55863.3
