<a href="https://colab.research.google.com/github/tanvirrahmanaz/Phitron/blob/main/Tanvir_Rahman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Email address: tanvirrahmanaz@gmail.com

In [2]:
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


# **Q1**. Create NumPy arrays from the ages and salaries data generated above. Print both arrays and display their dtype, ndim, shape, and size.


In [3]:
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)

# Print arrays
print("="*50)
print(f"The Ages are: {ages}")
print(f"The Salaries are: {salaries}")
print("="*50)

# dtype
print("\nData Type (dtype)")
print(f" - Ages dtype: {ages.dtype}")
print(f" - Salaries dtype: {salaries.dtype}")

# ndim
print("\nDimensions (ndim)")
print(f" - Ages ndim: {ages.ndim}")
print(f" - Salaries ndim: {salaries.ndim}")

# shape
print("\nShape")
print(f" - Ages shape: {ages.shape}")
print(f" - Salaries shape: {salaries.shape}")

# size
print("\nSize (Total Elements)")
print(f" - Ages size: {ages.size}")
print(f" - Salaries size: {salaries.size}")
print("="*50)


The Ages are: [38 50 29 39 42 44 59 45 33 32]
The Salaries are: [30189 49118 65773 83810 31899 86886 31267 61551 80680 41394]

Data Type (dtype)
 - Ages dtype: int64
 - Salaries dtype: int64

Dimensions (ndim)
 - Ages ndim: 1
 - Salaries ndim: 1

Shape
 - Ages shape: (10,)
 - Salaries shape: (10,)

Size (Total Elements)
 - Ages size: 10
 - Salaries size: 10


#Q2. Using the salaries array, find and print the highest and lowest salary values. Also, calculate and print the average salary and age using NumPy functions.

In [4]:
print("Maximum and Minimum Salaries")
print("------------------------------")
print("Maximum Salary:", salaries.max())
print("Minimum Salary:", salaries.min())

print("\nAverage Values")
print("---------------")
print("Average Salary:", np.average(salaries))
print("Average Age:", np.average(ages))

Maximum and Minimum Salaries
------------------------------
Maximum Salary: 86886
Minimum Salary: 30189

Average Values
---------------
Average Salary: 56256.7
Average Age: 41.1


#Q3. From the ages array, filter and print all ages greater than 30 using a boolean condition. Then count and print how many employees are older than 30.

In [5]:
# Filter ages greater than 30
ages_greater_than_30 = ages[ages > 30]
print("Ages greater than 30:")
print(ages_greater_than_30)

# Count how many are older than 30
count = np.sum(ages > 30)
print(f"\nNumber of people older than 30: {count}")

Ages greater than 30:
[38 50 39 42 44 59 45 33 32]

Number of people older than 30: 9


#Q4. Create a new NumPy array that increases every employee’s age by 5 years (without modifying the original array). Print the new updated ages array.

In [6]:
# Create a new array (without modifying the original)
update_ages = ages + 5

print("\nUpdated Ages (+5 years added):")
print(update_ages)
print("="*50)

# Verify that original array is unchanged
print("\nChecking Original Array Again (Unchanged):")
print(ages)
print("="*50)


Updated Ages (+5 years added):
[43 55 34 44 47 49 64 50 38 37]

Checking Original Array Again (Unchanged):
[38 50 29 39 42 44 59 45 33 32]


#Q5. Using NumPy, calculate the total salary expense (sum of all salaries) and the difference between the maximum and minimum salary. Print both results.

In [7]:
total_salary= sum(salaries)
print(total_salary)

max_salary = salaries.max()
min_salary = salaries.min()
print(max_salary, min_salary)

diff = max_salary - min_salary
print(diff)

562567
86886 30189
56697


##Pandas

#Q6. Load the employees.csv file into a Pandas DataFrame. Display the first 5 rows, and check basic info using info() and summary statistics using describe().

In [8]:
# Load CSV file into a DataFrame
df = pd.read_csv("employees.csv")

# Display the first 5 rows
print("="*60)
print("First 5 Rows of the Dataset:")
print(df.head())

# Display basic info about the DataFrame
print("\nBasic Information:")
print("="*60)
df.info()

# Display summary statistics (numerical columns)
print("\nSummary Statistics:")
print("="*60)
print(df.describe())

First 5 Rows of the Dataset:
   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes

Summary Statistics:
             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


#Q7.Display only the id, age, and salary columns. Then show the last 3 rows using tail().


In [9]:
# Select only id, age, and salary columns
subset = df[["id", "age", "salary"]]

print("="*60)
print("Selected Columns (id, age, salary):")
print(subset)

# Display the last 3 rows
print("\nLast 3 Rows:")
print(subset.tail(3))
print("="*60)

Selected Columns (id, age, salary):
   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311

Last 3 Rows:
   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311


#Q8. Filter the DataFrame to show only employees who work in the IT department. Print the result and show the total number of IT employees.

In [10]:
# Filter employees from the IT department
it_employees = df[df["dept"] == "IT"]
total_it_employees = len(it_employees)

print("="*60)
print("💻 Employees from IT Department:")
print(it_employees)

print("\n📊 Total Number of IT Employees:", total_it_employees)
print("="*60)

💻 Employees from IT Department:
   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT

📊 Total Number of IT Employees: 3


#Q9. Sort the DataFrame by salary in descending order and display the top 3 highest-paid employees along with their department and age.


In [11]:
# Sort DataFrame by salary (descending order)
sorted_df = df.sort_values(by="salary", ascending=False)

# Select top 3 highest-paid employees
top_3_employees = sorted_df.head(3)[["id", "age", "dept", "salary"]]

print("="*60)
print("Top 3 Highest-Paid Employees:")
print(top_3_employees)
print("="*60)

Top 3 Highest-Paid Employees:
   id  age     dept  salary
6   7   36  Finance   89735
7   8   40       IT   86101
0   1   56       HR   77191


#Q10. Replace all salary values greater than 80000 with 80000 using loc. Then calculate and print the new average salary of all employees after replacement.

In [13]:
df.loc[df["salary"] > 80000, "salary"] = 80000

new_average_salary = df["salary"].mean()


print("\nNew Average Salary after Replacement:", new_average_salary)



New Average Salary after Replacement: 55863.3
